Revert "US3987 remove dependencies on jquery-migrate"
This reverts commit 4ef5fd7b327abf3fe2a502e27f6f41371cac45df.

Fixes error:

Error: Mismatched anonymous define() module: undefined
http://requirejs.org/docs/errors.html#mismatch